version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - my_network

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test5
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - my_network
    ports:
      - "6379:6379"
  
  isolated:
    build: ./isolated
    ports:
      - "9999:9999"
    networks:
      - my_network

volumes:
  redis_data:

networks:
  my_network:
